### PR TITLE
update schema and routes for phone number

### PR DESCRIPTION
**Pull request by rebekahkwon**

### CODE REVIEW

**Comment by rkho** [comment]
Looks good to me.

**Comment by scottdixon** [comment]
Looks awesome! This is going to be great. Couple of suggestions:

Should triggerSMS be wrapped in "if phone number exists" ?
trigger-sms.js doesn't trigger callbacks.error() if there's an issue.

**Comment by rebekahkwon** [comment]
Good catch Scott! Tested for user phone before triggering sms notification.

**Comment by scottdixon** [comment]
Nice! Merging

**Comment by rebekahkwon** [comment]
Scott, you rockl. I learned a lot :)

**Pull request merged**
