### PR TITLE
Angular front end

### PR DESCRIPTION
**Pull request by rkho**
Hi, lots of changes:

1. Removed airports_v2.json file (redundant file)
2. Removed livereload dependency that kept giving us an error
3. Added a progress bar to differentiate between views
4. Data persists through refresh thanks to local storage
5. Linked up telephone field in modal to my code that sends it in an object to the sever

### CODE REVIEW

**Comment by garronmichael** [comment]
Review now, but looks great. Maybe add a max price to budget?

**Comment by garronmichael** [comment]
*Reviewing

**Comment by garronmichael** [comment]
And then just the airport name removal we talked about

**Comment by rebekahkwon** [comment]
Nice. Agree with showing cities and capping tix at 1200.

**Pull request closed without merging**
