### PR TITLE
Angular front end

### PR DESCRIPTION
**Pull request by rkho**
Okay, so.

Massive changes. Entire front-end has been overhauled, since UI-View was not working properly. I'll have to fix the CSS I broke that Scott worked on after implementing functionality.

### CODE REVIEW

**Comment by scottdixon** [comment]
:+1:

**Comment by garronmichael** [comment]
Ok. Merging now to and redeploying to azure on my local branch to make sure all changes go smoothly.

**Comment by rebekahkwon** [comment]
Okie doke. Thanks Garron.

**Comment by garronmichael** [comment]
Oh. Looks like like this isn't an auto merge. I'll handle it.

**Comment by rebekahkwon** [comment]
Great job Richard!

**Comment by rkho** [comment]
Thanks Garron!

**Pull request merged**
